### ISSUE TITLE
Another undithering technique called mdapt

### ISSUE THREAD

**Issue by RyanBram** [pornel/undither#1]
Hi, Kornel.

I just want to inform you about another technique of dedithering. It is called mdapt which stands for merge dithering and pseudo transparency. The algorirhm is created by an author with an alias sp00kyFox.

The comparison image is as follow:
Nearest neighbor
![Nearest neighbor](http://i.imgur.com/RFySmrr.png)
Mdapt + xBR
![Mdapt + xBR](http://i.imgur.com/K1lwKT7.png)

As you can see, there are many difference with those picture, especially in the health bar which is looked as semi transparent.

The explanation about algorithm can be found in http://libretro.com/forums/threads/340-mdapt-amp-gdapt-dithering-treatment-Updated-06-06-14

**Comment by kornelski** [comment]
Thanks for the tip. The tool looks really neat.

However, I don't think that's applicable to my program. The problem I focus on is recreating photorealistic images that have been converted to palette with floyd steinberg dithering, basically the reverse of pngquant. FS dithering doesn't have regularity that mdapt looks for. Images with automatically generated palettes don't have such fine-tuned high contrast edges that are suitable for line detection and enlargement.
