### ISSUE TITLE
tag: 'undither'?

### ISSUE THREAD

**Issue by zvezdochiot** [pornel/undither#4]
Subj.

**Comment by kornelski** [comment]
Which tag?

**Comment by zvezdochiot** [comment]
@kornelski say> Which tag?

https://github.com/kornelski/undither  
tags: paletted-images, palette, smoothing, dithering, smart-blur, reconstruction  
tags missing: rust, undither  
  
https://github.com/topics/rust  
https://github.com/topics/undither

**Comment by kornelski** [comment]
It's weird that it doesn't take project name into account!

Added
